name: Daily Commit and Push

on:
  schedule:
    - cron: '0 18 * * *' # Runs every day at 18:00 UTC

jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name 'shivaji02'
        git config --global user.email 'shivajimandapati@outlook.com'

    - name: Commit and Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git add .
        git commit -m "Daily update: $(date)"
        git push
